### ISSUE TITLE
Add support ModelEngine 4

### ISSUE THREAD

**Issue by Euphillya** [MagmaGuy/EliteMobs#173]
**Version Minecraft : **
[10:30:19 INFO]: This server is running Paper version 1.21.1-DEV-HEAD@5757f1f (2024-08-19T11:28:52Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
Error obtaining version information
Previous version: 1.21.1-38-e4b38b4 (MC: 1.21.1)

**Version EliteMobs**
[10:30:51 INFO]: EliteMobs version 9.1.8
[10:30:51 INFO]: Author: MagmaGuy

**Version ModelEngine :**
[10:31:09 INFO]: ModelEngine version R4.0.7
[10:31:09 INFO]: Author: Ticxo

**Config**
```yml
isEnabled: true
entityType: HUSK
name: $eventBossLevel &3MINOTAUR
level: dynamic
onSpawnBlockStates: []
onRemoveBlockStates: []
bossType: NORMAL
customModel: minotaur
```

**Description :**

I tried using FreeMinecraftModels and it works, but I need ModelEngine for Bedrock players.

When I put the ModelEngine resource pack in my Minecraft, the mobs have no texture, just the default mob.
